### ISSUE TITLE
Test der Usability

### ISSUE THREAD

**Issue by darthkali** [Maffotter/BeHop#67]
**Getestet mit:** Android Phone, PC
**Browser:** Chrome

**PC:**

- [x] **Profil: Wenn ich eine bereits bestehende E-Mail Adresse eingebe und dann speichere, erscheint keine Fehlermeldung !!!**
- [x] Bei den Products ist immer Sales Rot Markiert, auch wenn ich mir die "New In" anzeigen lasse
- [x] AboutUs Seite: Text geht über volle Breite. hier sollte etwas Platz nach Rechts und links gelassen werden
- [x] Das E-Mail Feld im Profil sollte breiter gestaltet werden, da bei langen Adressen diese abgeschnitten werden.
- [x] Profil: Der Weiße Balken unten wirkt wie ein übergroßer Footer
- [x] ShoppingCart: wenn ich bei mehreren Artikeln die Anzahl ändere und dann auf save klicke, wird nur das eine gespeichert und die anderen Zurückgesetzt. Ggf schwierig umzusetzen und daher nur als Anmerkung zu verstehen. 
- [x] Produkte: Man kann nach Neuste bzw Älteste Sortieren. Hier ist nicht ersichtlich, für was das Datum steht. Erscheinungsdatum, Aktualisierungsdatum, Preisbearbeitung...
- [x] Startseite: Wenn die Bilder Zoomen beim Hovern wird die Schrift abgeschnitten. ggf sollte man diese etwas weiter in das Bild versetzen

**Handy:**

- [x] Falsche darstellung auf dem Handy wenn ich die Lupe anwähle (siehe screenshot)
![Screenshot_20200222_212959_com android chrome](https://user-images.githubusercontent.com/46423967/75099020-34215100-55bd-11ea-967b-b1c72fb97485.jpg)

**Comment by kanton1998** [comment]
bitte korrigiere das selber, sind deine Sachen gewesen :)
